config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'users/new'
  get '/home', to: "static_pages#home"
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'

  get 'signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users

  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, 
        format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to users_path
    else
        flash[:errors] = ["Invalid combination"]
        redirect_back(fallback_location:"/")
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    render "static_pages/home"
  end

  def help
    render "static_pages/help"
  end

  def about
    render "static_pages/about"
  end

  def contact
    render "static_pages/contact"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    user = User.new(user_params)

    if user.save
      redirect_to users_url(@user)
     
    else
      flash[:errors] = user.errors.full_messages
      redirect_back(fallback_location:"/")
    end
  end

  private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
    def gravatar_for(user, options = { size: 80 })
        size = options[:size]
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
    <ul>
        <li><%= link_to "About", about_path %>  </li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><a href="https://news.railstutorial.org/">News</a></li>
        <li><%= link_to "Home", root_path %>  </li>
    </ul>
    </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Log in", login_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <%= render 'layouts/head' %>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <%= yield %>
            <%= render 'layouts/footer' %>
            <%= debug(params) if Rails.env.development? %>
        </div>
    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if flash[:errors] %>
    
    <% flash[:errors].each do |error| %>
        <p class="text-danger"><%= error %></p>
    <% end %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
    <h1>About</h1>
<p>
    The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
    Tutorial</em></a>, part of the
    <a href="https://www.learnenough.com/">Learn Enough</a> family of
    tutorials, is a
    <a href="https://www.railstutorial.org/book">book</a> and
    <a href="https://screencasts.railstutorial.org/">screencast series</a>
    to teach web development with
    <a href="https://rubyonrails.org/">Ruby on Rails</a>.
    This is the sample app for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
    Contact the Ruby on Rails Tutorial about the sample app at the
    <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
    Get help on the Ruby on Rails Tutorial at the
    <a href="https://www.railstutorial.org/help">Rails Tutorial Help page</a>.
    To get help on this sample app, see the
    <a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
    book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>
    <h2>
        This is the home page for the
        <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
    <%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"),
                                            "https://rubyonrails.org/" %>



   

app/views/users/_form.html.erb
<!--
# <% if @user.errors.any? %>
# <div id ="error_explanation">
#     <div class="alert alert-danger">
#         The form contains <%= @user.errors.count %> errors.
#     </div>

#     <ul>
#         <% @user.errors.full_messages.each do |msg| %>
#            <li> <%= msg %> </li>
#         <% end %>
#     </ul>
# </div>

# <% end %>

app/views/users/index.html.erb
<% content_for(:title, "Users") %>
<%= flash[:success] = "Welcome to the Sample App!" %>
<h1>Listing <%= pluralize(@users.length, "user") %>  in our Sample App</h1>
<table>
    <thead>
        <tr>
            <td>Name</td>
            <td>Email</td>
            <td>Action</td>
        </tr>
    </thead>

    <tbody>
    <% @users.each do |player| %>
        <tr>
            <td><%= player.name %></td>
            <td><%= player.email %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>


<div class="row">
    <div class="col-md-6 col-md-offset-3">
    
        
        <%= form_with(model: @user, local: true) do |f| %>
           
            <%= render partial: "shared/error_messages" %>
            <%= f.label :name %>       
            <%= f.text_field :name %>
            <%= f.label :email %>
            <%= f.email_field :email %>
            <%= f.label :password %>
            <%= f.password_field :password %>
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation %>
            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>

    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>